{% set name = "psmpy" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psmpy-{{ version }}.tar.gz
  sha256: 13dcda62a6745ec53d2ee6834e987f50415f8cb21e1a1d47bc8a9fd2daf317d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pytest-runner
    - pip
  run:
    - python
    - matplotlib-base
    - numpy
    - pandas
    - seaborn
    - scikit-learn
    - scipy

test:
  imports:
    - psmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/psmpy/
  summary: Propensity score matching for python and graphical plots
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dillonroach
