{% set name = "psmpy" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psmpy-{{ version }}.tar.gz
  sha256: 8946a78fbe86780c8f03a17885a4e501422202b3f8367e5b3df00d417ac3e8f5
  patches:
    - 0001-fix-imports.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pandas
    - seaborn
    - scikit-learn
    - scipy

test:
  imports:
    - psmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/psmpy/
  summary: Propensity score matching for python and graphical plots
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - dillonroach
