{% set name = "psmpy" %}
{% set version = "0.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/psmpy-{{ version }}.tar.gz
  sha256: 67628f909cc7b72629a611ea09e88802342793c92b7dbd44b32e0afb535e7aa4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pandas
    - seaborn
    - scikit-learn
    - scipy

test:
  imports:
    - psmpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/psmpy/
  summary: Propensity score matching for python and graphical plots
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dillonroach
